services:
  receiver:
    build:
      context: .
      dockerfile: apps/receiver/Dockerfile
    image: trading-receiver:latest
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    volumes:
      - trading-data:/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  trading-data:
  redis-data: