services:
  receiver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    environment:
      REDIS_URL: redis://redis:6379
      DB_TYPE: ${DB_TYPE:-sqlite}
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"