
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  receiver:
    build:
      context: .
      dockerfile: trading/receiver/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - DERIBIT_CLIENT_ID=${DERIBIT_CLIENT_ID}
      - DERIBIT_CLIENT_SECRET=${DERIBIT_CLIENT_SECRET}
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data: