services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - trading-network

  receiver:
    build:
      context: .
      dockerfile: src/receiver/deribit/Dockerfile
    container_name: trading-app-receiver
    env_file:
      - config/.env
    environment:
      - DB_BASE_PATH=/app/data
    volumes:
      - ./config:/app/config:ro
      - trading-data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trading-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    user: "1001:1001"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

volumes:
  redis-data:
  trading-data: 

networks:
  trading-network:
    driver: bridge
    