# ./docker-compose.yml
version: '3.9'

services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading-network

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    restart: unless-stopped
    volumes:
      - ./configuration:/app/configuration:ro
      - ./restful_api:/app/restful_api:ro
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trading-network

volumes:
  redis-data:

networks:
  trading-network:
    driver: bridge