#version: '3.9' dont add this line, it is not needed in the latest versions of Docker Compose

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - trading-network

  receiver:
    build:
      context: .
      dockerfile: src/receiver/deribit/Dockerfile
    env_file:
      - config/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_BASE_PATH=/app/data
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - trading-network

volumes:
  redis-data:

networks:
  trading-network:
    driver: bridge