services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  receiver:
    build:
      context: .
      dockerfile: src/receiver/Dockerfile  # Updated path
    environment:
      - REDIS_URL=redis://redis:6379
      - TZ=UTC
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    secrets:
      - source: deribit_client_id
        target: deribit_client_id
      - source: deribit_client_secret
        target: deribit_client_secret
    restart: unless-stopped
    # Remove port mapping since no web server exists
    # ports:
    #   - "8000:8000"

  executor:
    build:
      context: .
      dockerfile: src/executor/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - TZ=UTC
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    secrets:
      - source: deribit_client_id
        target: deribit_client_id
      - source: deribit_client_secret
        target: deribit_client_secret
    restart: unless-stopped

volumes:
  redis-data:  
secrets:
  deribit_client_id:
    file: ./secrets/client_id.txt
  deribit_client_secret:
    file: ./secrets/client_secret.txt