services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - trading-network

  receiver:
    build: .
    container_name: trading-app-receiver
    volumes:
      - ./config:/app/config:ro
      - trading-data:/app/data
    environment:
      - DB_BASE_PATH=/app/data
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    user: "1001:1001"

volumes:
  trading-data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind,uid=1001,gid=1001,rw

networks:
  trading-network:
    driver: bridge