# ./docker-compose.yml

services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading-network

  receiver:
    build:
      context: .
      dockerfile: trading_app/receiver/Dockerfile
    restart: unless-stopped
    volumes:
      - ./trading_app/configuration:/app/configuration:ro
      - ./trading_app/restful_api:/app/restful_api:ro
      - ./trading_app/shared:/app/shared:ro
      - ./data:/app/data 
    environment:
      REDIS_URL: redis://redis:6379 
      DB_TYPE: ${DB_TYPE:-sqlite}  # or postgres
      DB_BASE_PATH: /app/data
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"  # Expose health check port
    networks:
      - trading-network

volumes:
  redis-data: # This volume is for Redis data persistence
  trading-data: # This volume is for trading data, if needed

networks:
  trading-network:
    driver: bridge