version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  receiver:
    build:
      context: .
      dockerfile: apps/receiver/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis

  # Similar for other services

volumes:
  redis_data:
  sqlite_data:

  services:
  receiver:
    volumes:
      - ./shared/config/exchanges:/app/shared/config/exchanges:ro
      - ./shared/config/overrides:/app/shared/config/overrides:ro

  distributor:
    volumes:
      - ./shared/config/exchanges:/app/shared/config/exchanges:ro
      - ./shared/config/overrides:/app/shared/config/overrides:ro