services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - trading-network

  receiver:
    build:
      context: .
      dockerfile: src/receiver/deribit/Dockerfile
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    environment:
      REDIS_URL: redis://redis:6379
      DB_TYPE: ${DB_TYPE:-sqlite}
      CONFIG_DIR: /app/config
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - trading-network

volumes:
  redis-data:
  trading-data:

networks:
  trading-network:
    driver: bridge
