# src\services\receiver\docker-compose.yml

x-receiver-config: &receiver-config
  environment:
    - REDIS_URL=redis://redis:6379
  secrets:
    - deribit_client_id
    - deribit_client_secret
  healthcheck:
    test: ["CMD", "python", "-c", "import src.services.receiver.deribit.main"]
    interval: 30s