[deribit]
ws_url = "wss://test.deribit.com/ws/api/v2"
channels = ["trades.BTC-PERPETUAL.raw"]

[redis]
host = "redis"
port = 6379
stream_name = "raw_data_stream"
max_queue_size = 10000

[logging]
level = "INFO"
format = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"