[project]
name = "receiver"
version = "0.1.0"

dependencies = [
    "websockets>=12.0",
    "aioredis>=2.0.0",
    "oci",
    "tomli>=2.0.1",
    "python-dotenv>=1.0.0",
    "uvloop>=0.19.0"
]

[build-system]
requires = ["uv"]
build-backend = "uv"