
[project]
name = "shared"
version = "1.0.0"
dependencies = [
    "orjson>=3.10.18",
    "redis>=5.0.0,<6.0.0",
    "aiohttp>=3.12.7",
    "aiosqlite>=0.20.0,<1.0.0",
    "python-dotenv>=1.0.0,<2.0.0",
    "loguru>=0.7.0,<1.0.0",
    "dataclassy",
    "tomli>=2.0.0",
]
