[blocked_scanners]
list = [
    "censysinspect",
    "nmap",
    "nessus",
    "acunetix"
]

[rate_limiting]
global = 10

[headers]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Content-Security-Policy = "default-src 'self'"
Strict-Transport-Security = "max-age=63072000; includeSubDomains"